# Documentation https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-5.x

FROM elasticsearch:5
RUN cd /usr/share/elasticsearch \
    && bin/elasticsearch-plugin install analysis-phonetic \
    && bin/elasticsearch-plugin install analysis-icu

